### ISSUE TITLE
How to get predicted event type

### ISSUE THREAD

**Issue by hodorxxx** [Yueeeeeeee/MetaEvent#5]
Hi, I only find the evaluation metrics output through code. I'm wondering how to get the predicted event type of a test sentence through detection result. Thanks !

**Comment by Yueeeeeeee** [comment]
Hi,

in the few-shot case, you can refer to the target classes in the dataloader file (see [target classes](https://github.com/Yueeeeeeee/MetaEvent/blob/main/src/dataloader_fewevent.py#L133)). As for the zero-shot case, you can't directly print out the target classes because the zero-shot classification is a clustering-like process, the output predictions are the indices of cluster centroids of different event classes. The zero-shot label mapping process can be found [here](https://github.com/Yueeeeeeee/MetaEvent/blob/main/src/utils.py#L134).
